pipeline {
    agent any
    stages {
        stage('Setup Python Environment') {
            steps {
                script {
                    echo 'Creating a virtual environment, if not already created'
                    sh '''
                        if [ ! -d ".venv" ]; then
                            env_name=${1:-".venv"}
                            python3 -m venv "$env_name"
                            echo "The virtual environment '$env_name' has been created."
                        fi
                    '''

                    echo 'Activating the virtual environment'
                    sh '''
                        env_name=${1:-".venv"}
                        if [ ! -d "$env_name" ]; then
                            echo "Virtual environment '$env_name' not found. Use '$0 create [env_name]' to create."
                            return 1
                        fi
                        if [ -z "$VIRTUAL_ENV" ]; then
                            chmod +x ./$env_name/bin/activate
                            ./$env_name/bin/activate
                            echo "Virtual environment '$env_name' is activated."
                        else
                            echo "The virtual environment has already been activated."
                        fi
                    '''

                    echo 'Dependency installation'
                    sh '''
                        if [ ! -f "lab2/requirements.txt" ]; then
                            echo "File requirements.txt not found."
                            return 1
                        fi

                        # Check if all dependencies from requirements.txt are installed
                        for package in $(cat lab2/requirements.txt | cut -d '=' -f 1); do
                            if ! pip freeze | grep -q "^$package=="; then
                                echo "Dependency installation..."
                                pip install -r lab2/requirements.txt
                                echo "Dependencies installed."
                                return 0
                            fi
                        done

                        echo "All dependencies are already installed."
                    '''
                }
            }
        }
        stage('Create dataset') {
            steps {
                echo 'Start create dataset'
                sh 'python3 lab2/python_scripts/create_dataset.py'
                echo 'Finish create dataset'
            }
        }
        stage('Data preprocessing') {
            steps {
                echo 'Start data preprocessing'
                sh 'python3 lab2/python_scripts/data_preprocessing.py'
                echo 'Finish data preprocessing'
            }
        }
        stage('Train model') {
            steps {
                echo 'Start train model'
                sh 'python3 lab2/python_scripts/train_model.py'
                echo 'Finish train model'
            }
        }
        stage('Test model') {
            steps {
                echo 'Start test model'
                sh 'python3 lab2/python_scripts/test_model.py'
                echo 'Finish test model'
            }
        }
    }
    post {
        always {
            echo 'Pipeline has finished.'
        }
        success {
            echo 'Pipeline completed successfully.'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}